name: doctl 
version: '1.6.0'
summary: 'Digital Ocean command line tool'
description: |
  DigitalOcean's web based control panel provides a 
  convenient, point-and-click interface for managing 
  Droplets. There are, however, times when a command-line
  tool may be a preferable alternative; If you have many 
  Droplets to manage, need to administer Droplets from the 
  terminal without a graphical desktop available, or have 
  tasks which would benefit from a scriptable interface.

grade: stable
confinement: strict

apps:
  doctl:
    command: doctl
    plugs:
      - home
      - network

parts:
  doctl:
    source: https://github.com/digitalocean/doctl.git
    plugin: go
    go-importpath: github.com/digitalocean/doctl
    source-tag: v1.6.0
    build-packages:
      - git
    after:
      - go
  go:
    source-tag: go1.8.1
    build-packages: 
      - software-properties-common
    prepare: |
      sudo add-apt-repository -y ppa:snappy-dev/tools
      sudo add-apt-repository -y ppa:gophers/archive
      sudo apt update && sudo apt upgrade -y
